### PR TITLE
Issue 36

### PR DESCRIPTION
**Pull request by happy25**
bitrise not passing -> shit

### CODE REVIEW

**Comment by zawadzkip** [comment]
@happy25 it's not passing due to the keys file missing, has to do with the new way we are doing the keys file.

**Comment by happy25** [comment]
we can change the build to ignore it can't we?

**Comment by zawadzkip** [comment]
@happy25 we can remove it from building on the project, but then I'm pretty sure it won't be compiled into the app when we build the project on our dev machines.

**Comment by sorianog** [comment]
@zawadzkip, @happy25 updates?

**Pull request merged**
