### PR TITLE
Issue 67: Settings/Profile Page UI

### PR DESCRIPTION
**Pull request by zawadzkip**
Also updated some packages, that's why the extra project and config stuff was changed

### CODE REVIEW

**Comment by zawadzkip** [comment]
simulator screen shot jan 12 2017 8 55 30 pm
iPhone SE with random image for profile picture

**Comment by sorianog** [comment]
@zawadzkip Is Night Mode just a place holder text right now? (since it is not part of MVP)

**Comment by zawadzkip** [comment]
@sorianog correct, it is just a placeholder... are we not doing it for MVP at all? Should I pull it?

**Comment by sorianog** [comment]
@zawadzkip Yes pull it out please! :)

**Comment by zawadzkip** [comment]
simulator screen shot jan 12 2017 9 27 44 pm

**Comment by sorianog** [comment]
@zawadzkip This merge shall pass.

**Comment by zawadzkip** [comment]
@sorianog go ahead and merge and delete the branch if its good :)

**Pull request merged**
