### PR TITLE
adding images

### PR DESCRIPTION
**Pull request by zawadzkip**

### CODE REVIEW

**Review by sorianog — COMMENTED** [review]
Could you please provide screenshots of the images on iOS and Android to this PR as well? Please and thank you :)

**Comment by sorianog** [comment]
@zawadzkip Status of this PR?

**Comment by sorianog** [comment]
Ah okay, so android images were not added before, until now? (just saw your recent commits). Since we don't meet anymore as a team this week, it would be convenient if the screenshots for the images on iOS and Android being displayed in the app were added here. Thanks!

**Comment by happy25** [comment]
is the image supposed to be seen anywhere in the app other than the app logo in app selection?

**Comment by zawadzkip** [comment]
@happy25 no, this is only for iOS and Android app icons. iOS should also have some sort of launch screen with the logo

**Comment by happy25** [comment]
ship it!!!

**Pull request merged**
